language: go

go:
  - 1.13.x

install: true

script:
  - ./go.test.sh

env: GO111MODULE=auto CODECOV_TOKEN="b00b9ce7-4ad6-4d62-b590-16eb78a082ca"

after_success:
  - bash <(curl -s https://codecov.io/bash)
