// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	redis "github.com/gomodule/redigo/redis"
	mock "github.com/stretchr/testify/mock"
)

// Pool is an autogenerated mock type for the Pool type
type Pool struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Pool) Get() redis.Conn {
	ret := _m.Called()

	var r0 redis.Conn
	if rf, ok := ret.Get(0).(func() redis.Conn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.Conn)
		}
	}

	return r0
}
