// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// GetService provides a mock function with given fields: serviceName
func (_m *Store) GetService(serviceName string) ([]string, error) {
	ret := _m.Called(serviceName)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateService provides a mock function with given fields: serviceName, operation, Host
func (_m *Store) UpdateService(serviceName string, operation string, Host string) error {
	ret := _m.Called(serviceName, operation, Host)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(serviceName, operation, Host)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
